# Site settings
name: G2K
description: Appraisal Link

# Unsplash
unsplash_client_id:

# Social
facebook_username: test
twitter_username: test
google_plus_username: test
dribbble_username: test
github_username: test
instagram_username: test

#staff-appraisal : https://docs.google.com/forms/d/e/1FAIpQLSfimzzqYmi315SN71bl756AVwJZLilhqT4dQhSYFwv5QpvbiA/viewform?usp=sf_link
staff-appraisal : https://forms.gle/KXHVyAUPbammPujJA
